import pandas as pd


def read_sintrex(fname):
    """Read a file generated by a Sintrex CG-5 data dump and parse it to a dataframe"""
    return pd.read_csv(
        fname, 
        skiprows=36, 
        names=['Lat', 'Lon', 'Alt', 'grav', 'sd', 'tilt_x', 'tilt_y', 'temp', 'tide', 'dur', 'rej', 'time', 'decimal_date', 'terrain', 'date'],
        parse_dates=['date', 'time'],
        sep='\s+',
    )


if __name__ == '__main__': 
    import sys
    if len(sys.argv) < 3:
        print("Usage: python parse_sintrex.py <filename> <output_filename>")
        sys.exit(1)
    else:
        df = read_sintrex(sys.argv[1])
        df.rename(columns={'time': 'datetime'}).to_csv(sys.argv[2], index=False)

    